import { FacilityData, CompanionData } from './schema';

export const FACILITY_DATA: Record<string, FacilityData> = {
  arcane_study: {
    id: 'arcane_study',
    name: 'Arcane Study',
    category: 'magic',
    minLevel: 5,
    prerequisite: 'Ability to cast arcane spells or trained in Arcana',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'A place of quiet research containing desks and bookshelves for arcane study.',
    orders: ['maintain', 'trade', 'craft', 'research', 'empower'],
    benefits: {
      basic: '+1 item bonus to Arcana checks (fortune effect 1/turn)',
      advanced: '+2 item bonus to Arcana checks',
      master: 'Fortune effect 2/turn',
    },
    companions: ['octavia', 'magistra_elara'],
  },
  armory: {
    id: 'armory',
    name: 'Armory',
    category: 'combat',
    minLevel: 5,
    prerequisite: 'Trained in Crafting or Warfare Lore',
    defaultSize: 'roomy',
    canEnlarge: false,
    unique: false,
    description: 'Contains mannequins, weapon racks, and equipment storage for defenders.',
    orders: ['maintain', 'trade', 'craft'],
    benefits: {
      basic: '+1 item bonus to Crafting (weapons/armor/shields)',
      advanced: '+2 item bonus',
      enhanced: 'Stocked Armory: Defenders use d8s in combat',
      master: 'Defenders use d10s in combat',
    },
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    category: 'combat',
    minLevel: 5,
    prerequisite: 'Trained in Warfare Lore',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'Housing and training facilities for Bastion Defenders.',
    orders: ['maintain', 'trade', 'recruit'],
    benefits: {
      basic: 'Houses up to 10 defenders, recruit 1d4+1 defenders',
      advanced: 'Recruit 1d6+2 defenders',
      enhanced: 'Houses 20 defenders, recruit 1d8+3',
      master: 'Houses 30 defenders, recruit 1d10+4',
    },
  },
  garden: {
    id: 'garden',
    name: 'Garden',
    category: 'resource',
    minLevel: 5,
    prerequisite: 'Trained in Nature',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'Cultivated plots for growing herbs, vegetables, and magical plants.',
    orders: ['maintain', 'trade', 'harvest'],
    benefits: {
      basic: '+1 item bonus to Nature checks, harvest 1d4 consumables',
      advanced: '+2 item bonus, harvest 1d6 consumables',
      enhanced: 'Harvest 1d8 consumables',
      master: 'Harvest 1d10 consumables, rare plants available',
    },
    companions: ['kalikke_kanerah'],
  },
  library: {
    id: 'library',
    name: 'Library',
    category: 'social',
    minLevel: 5,
    prerequisite: 'Trained in Society',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'A collection of books and scrolls for research and knowledge.',
    orders: ['maintain', 'trade', 'research'],
    benefits: {
      basic: '+1 item bonus to Society checks, 2 reference books',
      advanced: '+2 item bonus, 3 reference books',
      enhanced: 'Can research 2 topics per turn',
      master: '4 reference books, fortune effect 2/turn',
    },
    companions: ['linzi'],
  },
  smithy: {
    id: 'smithy',
    name: 'Smithy',
    category: 'crafting',
    minLevel: 5,
    prerequisite: 'Expert in Crafting',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'A forge with anvils, tools, and materials for metalworking.',
    orders: ['maintain', 'trade', 'craft'],
    benefits: {
      basic: '+1 item bonus to Crafting (metal items)',
      advanced: '+2 item bonus, reduced material costs',
      enhanced: 'Can craft 2 items simultaneously',
      master: '+3 item bonus, craft 3 items simultaneously',
    },
    companions: ['regongar'],
  },
  workshop: {
    id: 'workshop',
    name: 'Workshop',
    category: 'crafting',
    minLevel: 5,
    prerequisite: 'Expert in Crafting',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'A versatile crafting space with various tools and workbenches.',
    orders: ['maintain', 'trade', 'craft', 'harvest'],
    benefits: {
      basic: '+1 item bonus to Crafting, 6 tool sets',
      advanced: '+2 item bonus, 9 tool sets',
      enhanced: 'Fortune effect 2/turn, uncommon items',
      master: '+3 item bonus, craft 3 items per turn',
    },
    companions: ['jubilost', 'nok_nok'],
  },
  war_room: {
    id: 'war_room',
    name: 'War Room',
    category: 'combat',
    minLevel: 9,
    prerequisite: 'Expert in Society or Warfare Lore',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'Strategic planning center with maps and tactical information.',
    orders: ['maintain', 'trade', 'research', 'scout'],
    benefits: {
      basic: '+1 to Warfare Lore checks',
      advanced: '+2 bonus, improved scouting range',
      enhanced: 'Can scout 2 regions per turn',
      master: 'Auto-success on basic scouting',
    },
    companions: ['ekundayo', 'amiri'],
  },
  greenhouse: {
    id: 'greenhouse',
    name: 'Greenhouse',
    category: 'resource',
    minLevel: 9,
    prerequisite: 'Expert in Nature',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'An enclosed structure for growing exotic and delicate plants.',
    orders: ['maintain', 'trade', 'harvest', 'craft'],
    benefits: {
      basic: 'Grow rare plants, +1 to Nature checks',
      advanced: '+2 bonus, grow magical reagents',
      enhanced: 'Harvest exotic components',
      master: 'Grow legendary plant specimens',
    },
  },
  laboratory: {
    id: 'laboratory',
    name: 'Laboratory',
    category: 'magic',
    minLevel: 9,
    prerequisite: 'Expert in Arcana or Crafting',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'Alchemical and magical experimentation facility.',
    orders: ['maintain', 'trade', 'craft', 'research'],
    benefits: {
      basic: '+1 to alchemical crafting',
      advanced: '+2 bonus, create rare elixirs',
      enhanced: 'Craft 2 items simultaneously',
      master: '+3 bonus, experimental formulas',
    },
    companions: ['octavia', 'jubilost'],
  },
  sanctuary: {
    id: 'sanctuary',
    name: 'Sanctuary',
    category: 'magic',
    minLevel: 9,
    prerequisite: 'Ability to cast divine spells',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'A sacred space for divine worship and healing.',
    orders: ['maintain', 'trade', 'craft', 'recruit', 'empower'],
    benefits: {
      basic: '+1 to Religion checks, spell refreshment',
      advanced: '+2 bonus, enhanced healing',
      enhanced: 'Recruit divine defenders',
      master: 'Powerful divine boons',
    },
    companions: ['tristian'],
  },
  scriptorium: {
    id: 'scriptorium',
    name: 'Scriptorium',
    category: 'social',
    minLevel: 9,
    prerequisite: 'Expert in Society or Scribing Lore',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'A workspace for scribes, copyists, and document creation.',
    orders: ['maintain', 'trade', 'craft', 'research'],
    benefits: {
      basic: '+1 to scroll crafting',
      advanced: '+2 bonus, craft 2 scrolls per turn',
      enhanced: 'Research 2 topics per turn',
      master: 'Craft scrolls up to 8th rank',
    },
    companions: ['linzi'],
  },
  training_area: {
    id: 'training_area',
    name: 'Training Area',
    category: 'combat',
    minLevel: 9,
    prerequisite: 'Expert in Athletics or Warfare Lore',
    defaultSize: 'vast',
    canEnlarge: false,
    unique: false,
    description: 'Open courtyard or gymnasium for combat training.',
    orders: ['maintain', 'trade', 'recruit', 'empower'],
    benefits: {
      basic: '+1 to Athletics, recruit 2d4 defenders',
      advanced: '+2 bonus, recruit 2d4+2 defenders',
      enhanced: 'Training stance: resistance 2',
      master: 'Resistance 4, recruit 2d8+4 defenders',
    },
    companions: ['valerie', 'nok_nok', 'amiri'],
  },
  teleportation_circle: {
    id: 'teleportation_circle',
    name: 'Teleportation Circle',
    category: 'magic',
    minLevel: 9,
    prerequisite: 'Expert in Arcana or Occultism',
    defaultSize: 'cramped',
    canEnlarge: false,
    unique: true,
    description: 'A permanent magical circle for instant travel.',
    orders: ['maintain', 'trade', 'recruit', 'empower'],
    benefits: {
      basic: 'Teleport once per turn',
      advanced: 'Recruit visiting spellcasters',
      enhanced: '3 attuned locations',
      master: '4 attuned locations',
    },
  },
  archive: {
    id: 'archive',
    name: 'Archive',
    category: 'social',
    minLevel: 13,
    prerequisite: 'Upgrade from Library, Master in Society',
    defaultSize: 'roomy',
    canEnlarge: true,
    unique: false,
    description: 'Repository of valuable books, maps, and scrolls.',
    orders: ['maintain', 'trade', 'research'],
    benefits: {
      basic: '+1 to Research checks',
      enhanced: '+2 bonus, 2 rare reference books',
      master: 'Research 3 topics, +2 Recall Knowledge bonus',
    },
    companions: ['linzi', 'jubilost'],
  },
  menagerie: {
    id: 'menagerie',
    name: 'Menagerie',
    category: 'resource',
    minLevel: 13,
    prerequisite: 'Master in Nature',
    defaultSize: 'vast',
    canEnlarge: true,
    unique: false,
    description: 'Enclosures for exotic creatures and beasts.',
    orders: ['maintain', 'trade', 'recruit'],
    benefits: {
      basic: 'House 4 Large creatures',
      enhanced: '+1 to creature care',
      master: '+2 bonus, house 8 Large creatures',
    },
  },
  reliquary: {
    id: 'reliquary',
    name: 'Reliquary',
    category: 'magic',
    minLevel: 13,
    prerequisite: 'Upgrade from Sanctuary, Master in Religion',
    defaultSize: 'cramped',
    canEnlarge: false,
    unique: true,
    description: 'Vault for sacred objects and relics.',
    orders: ['maintain', 'trade', 'empower', 'harvest'],
    benefits: {
      basic: 'Divine protection, blessing tokens',
      enhanced: 'Resistance 5 to evil damage',
      master: 'Resistance 10, petition deity',
    },
    companions: ['tristian'],
  },
  demiplane: {
    id: 'demiplane',
    name: 'Demiplane',
    category: 'magic',
    minLevel: 17,
    prerequisite: 'Legendary in Arcana or Occultism',
    defaultSize: 'vast',
    canEnlarge: false,
    unique: true,
    description: 'A pocket dimension accessible from your Bastion.',
    orders: ['maintain', 'empower'],
    benefits: {
      master: 'Perfect security, time manipulation, custom environment',
    },
  },
  guildhall: {
    id: 'guildhall',
    name: 'Guildhall',
    category: 'social',
    minLevel: 17,
    prerequisite: 'Master in relevant skill',
    defaultSize: 'vast',
    canEnlarge: true,
    unique: false,
    description: 'Headquarters for a guild of 50+ members.',
    orders: ['maintain', 'trade', 'recruit'],
    benefits: {
      master: 'Guild assignments, specialized services',
    },
  },
};

export const COMPANION_DATA: Record<string, CompanionData> = {
  linzi: {
    id: 'linzi',
    name: 'Linzi',
    title: 'The Chronicler',
    facility: 'library, archive, scriptorium',
    bonus: '+2 item bonus to Research, research 2 topics per turn',
    questRequired: true,
    questName: 'Missing Pages',
    questDescription: 'Discover and recover lost historical texts from a ruined archive.',
  },
  ekundayo: {
    id: 'ekundayo',
    name: 'Ekundayo',
    title: 'The Tracker',
    facility: 'war_room',
    bonus: 'Scout orders auto-succeed, +50% scouting range',
    questRequired: true,
    questName: 'Retribution',
    questDescription: 'Track down the trolls who killed his family and help him find closure.',
  },
  nok_nok: {
    id: 'nok_nok',
    name: 'Nok-Nok',
    title: 'Goblin Hero',
    facility: 'training_area, workshop',
    bonus: 'Work 2 facilities simultaneously (combat/traps), +1 to Recruit',
    questRequired: true,
    questName: 'The Goblin King',
    questDescription: 'Prove himself as the prophesied Goblin King among the tribes.',
  },
  valerie: {
    id: 'valerie',
    name: 'Valerie',
    title: 'Disciplined Captain',
    facility: 'armory, training_area',
    bonus: 'Equipment orders -10% cost, Recruit +2 defenders',
    questRequired: true,
    questName: 'False Faces',
    questDescription: 'Defeat Sir Fredero Sinnet and the green hag manipulating their conflict.',
  },
  jubilost: {
    id: 'jubilost',
    name: 'Jubilost',
    title: 'Master Cartographer',
    facility: 'laboratory, archive',
    bonus: '-25% crafting time, enhanced precision, superior cartography',
    questRequired: true,
    questName: 'The Inconsequent Debates',
    questDescription: 'Uncover gnome origins and participate in debates hosted by Shyka the Many.',
  },
  tristian: {
    id: 'tristian',
    name: 'Tristian',
    title: 'Sanctuary Keeper',
    facility: 'sanctuary, reliquary',
    bonus: 'Divine services extra income, enhanced healing',
    questRequired: true,
    questName: 'Kingdom of the Cleansed',
    questDescription: 'Defeat the chaos cult threatening to inflict aging curses.',
  },
  amiri: {
    id: 'amiri',
    name: 'Amiri',
    title: 'War Leader',
    facility: 'training_area, war_room, barracks',
    bonus: 'Stocked Armory uses d10s for casualties',
    questRequired: true,
    questName: 'Blood Calling',
    questDescription: 'Free the Six Bears from undead pursuit and embrace her role as war leader.',
  },
  kalikke_kanerah: {
    id: 'kalikke_kanerah',
    name: 'Kalikke & Kanerah',
    title: 'Elemental Twins',
    facility: 'greenhouse, demiplane, laboratory',
    bonus: 'Work 2 facilities with elemental expertise, enhanced magical crafting',
    questRequired: true,
    questName: 'Separating the Twins',
    questDescription: 'Break the balor\'s curse binding two souls into one body.',
  },
  harrim: {
    id: 'harrim',
    name: 'Harrim',
    title: 'Philosophical Counselor',
    facility: 'any',
    bonus: 'Roll Bastion Events twice, choose result',
    questRequired: false,
  },
  octavia: {
    id: 'octavia',
    name: 'Octavia',
    title: 'Arcane Researcher',
    facility: 'arcane_study, laboratory',
    bonus: '+2 item bonus to magical crafting, spell research',
    questRequired: false,
  },
  regongar: {
    id: 'regongar',
    name: 'Regongar',
    title: 'Destructive Innovator',
    facility: 'smithy, training_area',
    bonus: 'Enhanced weapon crafting, intimidation problem-solving',
    questRequired: false,
  },
};

export const ORDER_SKILLS: Record<OrderType, { primary: string; alternatives: string[] }> = {
  maintain: { primary: 'None', alternatives: [] },
  trade: { primary: 'Society', alternatives: ['Mercantile Lore', 'Facility-specific Lore'] },
  craft: { primary: 'Crafting', alternatives: ['Appropriate Lore'] },
  empower: { primary: 'Arcana/Nature/Occultism/Religion', alternatives: ['Appropriate Lore'] },
  harvest: { primary: 'Nature', alternatives: ['Agriculture Lore', 'Herbalism Lore'] },
  recruit: { primary: 'Society', alternatives: ['Warfare Lore', 'Relevant Lore'] },
  research: { primary: 'Society', alternatives: ['Any suitable Lore'] },
  scout: { primary: 'Society/Survival', alternatives: ['Appropriate Lore'] },
};
